name: SmallRye Build

on:
  push:
    branches: 
      - main
    paths-ignore:
      - '.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE'
      - 'NOTICE'
      - 'README*'
  pull_request:
    paths-ignore:
      - '.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE'
      - 'NOTICE'
      - 'README*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [11, 16]
    name: build with jdk ${{matrix.java}}

    steps:
      - uses: actions/checkout@v2
        name: checkout

      - uses: actions/setup-java@v1
        name: set up jdk ${{matrix.java}}
        with:
          java-version: ${{matrix.java}}

      - name: build with maven
        run: mvn -B formatter:validate verify --file pom.xml

  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        java: [11, 16]
    name: build with jdk ${{matrix.java}} windows

    steps:
      - uses: actions/checkout@v2
        name: checkout

      - uses: actions/setup-java@v1
        name: set up jdk ${{matrix.java}}
        with:
          java-version: ${{matrix.java}}

      - name: build with maven
#        Skip integration tests. TestContainers does not support Windows Server 2019: https://github.com/testcontainers/testcontainers-java/issues/2960
        run: mvn -B formatter:validate test --file pom.xml

  quality:
    needs: [build]
    if: github.event_name == 'push' && github.repository_owner == 'smallrye'
    runs-on: ubuntu-latest
    name: quality

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: sonar
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
        run: mvn -B verify --file pom.xml -Pcoverage javadoc:javadoc sonar:sonar -Dsonar.login=$SONAR_TOKEN
